### ISSUE TITLE
蓝瘦

### ISSUE THREAD

**Issue by ChenAt** [Hitomis/TransferImage#3]
最近优化一下项目的一些ui，刚好有这么个动画需求，在网上找了一圈没发现合适的，自己造了个轮子，这几天才发现了这个项目。。 心好累
大概过了一下你的库，扩展性和代码都不错，nb，不过有两个建议：
1.看 qq 或者 微信，一旦原图加载完毕第二次打开的时候应该就直接是原图了，就不该还能看见缩略图了。
2.最好对 view 做一个缓存，添加到 contentView 的那个 view 可以做成 activity 级别的单例，当 activity 销毁的时候再移除？
我说的有误或者你有其他见解可以指出 ,嘻嘻

**Comment by Hitomis** [comment]
嗯，这两点建议我也表示很赞同，谢谢指出不足之处。
这几天就开始着手改善一下。
Thx~
