### ISSUE TITLE
GridView无法实现GroupImageActivity效果

### ISSUE THREAD

**Issue by wudaren** [Hitomis/TransferImage#4]
像微信那样，点击九宫格GridView Item进入预览，在预览Activity应该也是Viewpager左右滑动的，现在demo给出的GridView 预览只能预览当前一个图片，所以尝试把代码改成GroupImageActivity的方式，发现在预览图片界面会发生空指针异常，containnerLayoutMap的size远远小于传入的ImageViewList的size,不知道containnerLayoutMap的加入数据逻辑是否有问题，并且GridView 传入的一组ImageViewList 还要手动写循环构造一个List才能匹配setOriginImages参数

**Comment by Hitomis** [comment]
能把你的代码贴一下么？

**Comment by wudaren** [comment]
![image](https://cloud.githubusercontent.com/assets/7829728/22874758/d395c99a-f202-11e6-855c-1d93c0e16f87.png)

**Comment by wudaren** [comment]
这是基于你demo代码GridView Adapter直接修改测试的
![image](https://cloud.githubusercontent.com/assets/7829728/22874797/1d95d468-f203-11e6-8519-05f7b30a8c9f.png)

**Comment by Hitomis** [comment]
这个问题已修复，并且重写编写了GroupImageActivity代码，里面是九宫格样式的 Demo，原GroupImageActivity中代码移到了TouchMoveImageActivity 中

**Comment by wudaren** [comment]
谢谢作者分享！
