### ISSUE TITLE
虽然你写了注释， 这个方法没有看懂这是在做什么呢， 

### ISSUE THREAD

**Issue by tianshaokai** [Hitomis/TransferImage#6]
![image](https://cloud.githubusercontent.com/assets/6706496/23008167/dbf7d2b6-f448-11e6-98fd-72454f4d1034.png)

**Comment by Hitomis** [comment]
这个方法是获取 GridView 列表中的 ImageView ，然后放入 List 集合中。以备 TransferImage 使用

**Comment by tianshaokai** [comment]
我是自定义的九宫格控件，不传这个可以吗

**Comment by Hitomis** [comment]
不传的话，就没了过渡动画
