### ISSUE TITLE
图片 和下边的指示器 出现了时间差， 没有同时显示出来

### ISSUE THREAD

**Issue by tianshaokai** [Hitomis/TransferImage#7]
感觉怪怪的，其他倒没什么

**Comment by tianshaokai** [comment]
对了如果在adapter 里怎么调用啊

**Comment by Hitomis** [comment]
图片和指示器显示的时机确实就是这个样子，这个不必在意；
Demo 中的代码就是在 adapter  里调用的。

**Comment by tianshaokai** [comment]
没有继承BaseAdapter 都是默认的adapter 的写法，有时间我改成 一个打开 activity 加载的
