### ISSUE TITLE
多点触控

### ISSUE THREAD

**Issue by Merbn** [Hitomis/TransferImage#8]
TouchMoveImage  多点触控 会有问题

**Comment by Hitomis** [comment]
谢谢指出问题，不过还请清楚到底是出了什么问题~

**Comment by Merbn** [comment]
比如 ：一个手指按住一个图。另一个手指点另一张图。  会出现 两张图消失了的现象。

**Comment by Hitomis** [comment]
好的，谢谢您提出的问题，这个问题目前已经解决了，请更新代码查看。
